// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: coffee.sql

package db

import (
	"context"
)

const createCoffee = `-- name: CreateCoffee :one
INSERT INTO coffee (user_id, uuid, name, origin, roast, process, price) 
VALUES ($1, gen_random_uuid(), $2, $3, $4, $5, $6)
RETURNING id, user_id, uuid, name, origin, roast, process, price, created_at, updated_at, deleted_at
`

type CreateCoffeeParams struct {
	UserID  int32
	Name    string
	Origin  string
	Roast   string
	Process string
	Price   int32
}

func (q *Queries) CreateCoffee(ctx context.Context, arg CreateCoffeeParams) (Coffee, error) {
	row := q.db.QueryRow(ctx, createCoffee,
		arg.UserID,
		arg.Name,
		arg.Origin,
		arg.Roast,
		arg.Process,
		arg.Price,
	)
	var i Coffee
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Uuid,
		&i.Name,
		&i.Origin,
		&i.Roast,
		&i.Process,
		&i.Price,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteCoffee = `-- name: DeleteCoffee :exec
DELETE FROM coffee 
WHERE id = $1
`

func (q *Queries) DeleteCoffee(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteCoffee, id)
	return err
}

const getCoffeeByID = `-- name: GetCoffeeByID :one
SELECT id, user_id, uuid, name, origin, roast, process, price, created_at, updated_at, deleted_at FROM coffee 
WHERE id = $1
`

func (q *Queries) GetCoffeeByID(ctx context.Context, id int32) (Coffee, error) {
	row := q.db.QueryRow(ctx, getCoffeeByID, id)
	var i Coffee
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Uuid,
		&i.Name,
		&i.Origin,
		&i.Roast,
		&i.Process,
		&i.Price,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCoffeesByUserID = `-- name: GetCoffeesByUserID :many
SELECT id, user_id, uuid, name, origin, roast, process, price, created_at, updated_at, deleted_at FROM coffee 
WHERE user_id = $1
`

func (q *Queries) GetCoffeesByUserID(ctx context.Context, userID int32) ([]Coffee, error) {
	rows, err := q.db.Query(ctx, getCoffeesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Coffee
	for rows.Next() {
		var i Coffee
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Uuid,
			&i.Name,
			&i.Origin,
			&i.Roast,
			&i.Process,
			&i.Price,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCoffee = `-- name: UpdateCoffee :exec
UPDATE coffee 
SET name = $1, origin = $2, roast = $3, process = $4, price = $5, updated_at = CURRENT_TIMESTAMP
WHERE id = $6
`

type UpdateCoffeeParams struct {
	Name    string
	Origin  string
	Roast   string
	Process string
	Price   int32
	ID      int32
}

func (q *Queries) UpdateCoffee(ctx context.Context, arg UpdateCoffeeParams) error {
	_, err := q.db.Exec(ctx, updateCoffee,
		arg.Name,
		arg.Origin,
		arg.Roast,
		arg.Process,
		arg.Price,
		arg.ID,
	)
	return err
}
