// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Coffee struct {
	ID        int32
	UserID    int32
	Uuid      pgtype.UUID
	Name      string
	Origin    string
	Roast     string
	Process   string
	Price     int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type User struct {
	ID           int32
	Uuid         pgtype.UUID
	Name         string
	Phone        string
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}
